import type { MetadataRoute } from 'next';

export default function sitemap(): MetadataRoute.Sitemap {
  const now = new Date();

  return [
    {
      url: 'https://www.girocodegenerator.com',
      lastModified: now,
      changeFrequency: 'monthly',
      priority: 1,
    },
    {
      url: 'https://www.girocodegenerator.com/en',
      lastModified: now,
      changeFrequency: 'monthly',
      priority: 0.9,
    },
    {
      url: 'https://www.girocodegenerator.com/fr',
      lastModified: now,
      changeFrequency: 'monthly',
      priority: 0.9,
    },
    {
      url: 'https://www.girocodegenerator.com/es',
      lastModified: now,
      changeFrequency: 'monthly',
      priority: 0.9,
    },
    {
      url: 'https://www.girocodegenerator.com/wissen/girocode',
      lastModified: now,
      changeFrequency: 'monthly',
      priority: 0.8,
    },
    {
      url: 'https://www.girocodegenerator.com/en/wissen/girocode',
      lastModified: now,
      changeFrequency: 'monthly',
      priority: 0.8,
    },
    {
      url: 'https://www.girocodegenerator.com/fr/wissen/girocode',
      lastModified: now,
      changeFrequency: 'monthly',
      priority: 0.7,
    },
    {
      url: 'https://www.girocodegenerator.com/es/wissen/girocode',
      lastModified: now,
      changeFrequency: 'monthly',
      priority: 0.7,
    },
    {
      url: 'https://www.girocodegenerator.com/wissen/epc-standard',
      lastModified: now,
      changeFrequency: 'monthly',
      priority: 0.8,
    },
    {
      url: 'https://www.girocodegenerator.com/en/wissen/epc-standard',
      lastModified: now,
      changeFrequency: 'monthly',
      priority: 0.8,
    },
    {
      url: 'https://www.girocodegenerator.com/fr/wissen/epc-standard',
      lastModified: now,
      changeFrequency: 'monthly',
      priority: 0.7,
    },
    {
      url: 'https://www.girocodegenerator.com/es/wissen/epc-standard',
      lastModified: now,
      changeFrequency: 'monthly',
      priority: 0.7,
    },
    {
      url: 'https://www.girocodegenerator.com/wissen/iban-bic',
      lastModified: now,
      changeFrequency: 'monthly',
      priority: 0.8,
    },
    {
      url: 'https://www.girocodegenerator.com/en/wissen/iban-bic',
      lastModified: now,
      changeFrequency: 'monthly',
      priority: 0.8,
    },
    {
      url: 'https://www.girocodegenerator.com/fr/wissen/iban-bic',
      lastModified: now,
      changeFrequency: 'monthly',
      priority: 0.7,
    },
    {
      url: 'https://www.girocodegenerator.com/es/wissen/iban-bic',
      lastModified: now,
      changeFrequency: 'monthly',
      priority: 0.7,
    },
    {
      url: 'https://www.girocodegenerator.com/wissen/betrag-und-zweck',
      lastModified: now,
      changeFrequency: 'monthly',
      priority: 0.7,
    },
    {
      url: 'https://www.girocodegenerator.com/en/wissen/betrag-und-zweck',
      lastModified: now,
      changeFrequency: 'monthly',
      priority: 0.7,
    },
    {
      url: 'https://www.girocodegenerator.com/fr/wissen/betrag-und-zweck',
      lastModified: now,
      changeFrequency: 'monthly',
      priority: 0.7,
    },
    {
      url: 'https://www.girocodegenerator.com/es/wissen/betrag-und-zweck',
      lastModified: now,
      changeFrequency: 'monthly',
      priority: 0.7,
    },
    {
      url: 'https://www.girocodegenerator.com/wissen/rechnung',
      lastModified: now,
      changeFrequency: 'monthly',
      priority: 0.7,
    },
    {
      url: 'https://www.girocodegenerator.com/en/wissen/rechnung',
      lastModified: now,
      changeFrequency: 'monthly',
      priority: 0.7,
    },
    {
      url: 'https://www.girocodegenerator.com/fr/wissen/rechnung',
      lastModified: now,
      changeFrequency: 'monthly',
      priority: 0.7,
    },
    {
      url: 'https://www.girocodegenerator.com/es/wissen/rechnung',
      lastModified: now,
      changeFrequency: 'monthly',
      priority: 0.7,
    },
    {
      url: 'https://www.girocodegenerator.com/wissen/banking-apps',
      lastModified: now,
      changeFrequency: 'monthly',
      priority: 0.7,
    },
    {
      url: 'https://www.girocodegenerator.com/en/wissen/banking-apps',
      lastModified: now,
      changeFrequency: 'monthly',
      priority: 0.7,
    },
    {
      url: 'https://www.girocodegenerator.com/fr/wissen/banking-apps',
      lastModified: now,
      changeFrequency: 'monthly',
      priority: 0.7,
    },
    {
      url: 'https://www.girocodegenerator.com/es/wissen/banking-apps',
      lastModified: now,
      changeFrequency: 'monthly',
      priority: 0.7,
    },
    {
      url: 'https://www.girocodegenerator.com/wissen/scannen',
      lastModified: now,
      changeFrequency: 'monthly',
      priority: 0.6,
    },
    {
      url: 'https://www.girocodegenerator.com/en/wissen/scannen',
      lastModified: now,
      changeFrequency: 'monthly',
      priority: 0.6,
    },
    {
      url: 'https://www.girocodegenerator.com/fr/wissen/scannen',
      lastModified: now,
      changeFrequency: 'monthly',
      priority: 0.6,
    },
    {
      url: 'https://www.girocodegenerator.com/es/wissen/scannen',
      lastModified: now,
      changeFrequency: 'monthly',
      priority: 0.6,
    },
    {
      url: 'https://www.girocodegenerator.com/ueber-uns',
      lastModified: now,
      changeFrequency: 'monthly',
      priority: 0.6,
    },
    {
      url: 'https://www.girocodegenerator.com/en/ueber-uns',
      lastModified: now,
      changeFrequency: 'monthly',
      priority: 0.5,
    },
    {
      url: 'https://www.girocodegenerator.com/fr/ueber-uns',
      lastModified: now,
      changeFrequency: 'monthly',
      priority: 0.5,
    },
    {
      url: 'https://www.girocodegenerator.com/es/ueber-uns',
      lastModified: now,
      changeFrequency: 'monthly',
      priority: 0.5,
    },
    {
      url: 'https://www.girocodegenerator.com/fuer-entwickler',
      lastModified: now,
      changeFrequency: 'monthly',
      priority: 0.7,
    },
    {
      url: 'https://www.girocodegenerator.com/en/fuer-entwickler',
      lastModified: now,
      changeFrequency: 'monthly',
      priority: 0.6,
    },
    {
      url: 'https://www.girocodegenerator.com/fr/fuer-entwickler',
      lastModified: now,
      changeFrequency: 'monthly',
      priority: 0.6,
    },
    {
      url: 'https://www.girocodegenerator.com/es/fuer-entwickler',
      lastModified: now,
      changeFrequency: 'monthly',
      priority: 0.6,
    },
    {
      url: 'https://www.girocodegenerator.com/impressum',
      lastModified: now,
      changeFrequency: 'yearly',
      priority: 0.3,
    },
    {
      url: 'https://www.girocodegenerator.com/en/impressum',
      lastModified: now,
      changeFrequency: 'yearly',
      priority: 0.3,
    },
    {
      url: 'https://www.girocodegenerator.com/fr/impressum',
      lastModified: now,
      changeFrequency: 'yearly',
      priority: 0.3,
    },
    {
      url: 'https://www.girocodegenerator.com/es/impressum',
      lastModified: now,
      changeFrequency: 'yearly',
      priority: 0.3,
    },
    {
      url: 'https://www.girocodegenerator.com/datenschutz',
      lastModified: now,
      changeFrequency: 'yearly',
      priority: 0.3,
    },
    {
      url: 'https://www.girocodegenerator.com/en/datenschutz',
      lastModified: now,
      changeFrequency: 'yearly',
      priority: 0.3,
    },
    {
      url: 'https://www.girocodegenerator.com/fr/datenschutz',
      lastModified: now,
      changeFrequency: 'yearly',
      priority: 0.3,
    },
    {
      url: 'https://www.girocodegenerator.com/es/datenschutz',
      lastModified: now,
      changeFrequency: 'yearly',
      priority: 0.3,
    },
  ];
}

